# הגדרות עבור PostgreSQL
postgresql:
  architecture: standalone
  auth:
    database: "my_database_name"     # שם בסיס הנתונים שיווצר
    existingSecret: "my-pg-secret"  # שם ה-Secret הקיים המכיל סיסמה
