apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: statuspage
  template:
    metadata:
      labels:
        app: statuspage
    spec:
      containers:
      - name: statuspage-container
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/yarin-noa-project:latest
        ports:
          - containerPort: 8000
        env:
          - name: DEBUG
            value: "True"
          - name: SECRET_KEY
            value: "super-secret-temporary-key"